kind: pipeline
type: docker
name: rust-nightly

steps:
  - name: test
    image: rustlang/rust:nightly
    commands:
      - cargo test --verbose --all

  - name: build
    image: rustlang/rust:nightly
    commands:
      - cargo build --verbose --all

---
kind: pipeline
type: docker
name: rust-1-50

steps:
  - name: test
    image: rust:1.50
    commands:
      - cargo test --verbose --all

  - name: build
    image: rust:1.50
    commands:
      - cargo build --verbose --all
